workflows:
  dcm-analysis:
    name: DCM avoid-unrelated-type-assertions
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      # Sets the Flutter version to the version from fvm_config.json.
      flutter: fvm
      groups:
        - dcm_key
    scripts:
      - name: install dcm on codemagic
        script: |
          brew tap CQLabs/dcm
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew install dcm
      - name: Install flutter packages
        script: cd app && flutter pub get
      - name: Run DCM Analysis with License key
        script: |
          cd app
          mkdir -p dcm-results
          dcm analyze --ci-key=$DCM_KEY --email=$DCM_EMAIL_ID lib --reporter=json --json-path=$CM_BUILD_DIR/app/dcm-results/dcm.json
          test_report: app/dcm-results/dcm.json
